[package]
name = "assembly-memo"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
mollusk-svm = "0.7.2"
solana-instruction = "3.1.0"
solana-address = "2.0.0"

[features]
test-sbf = []